name: poetry
adopt-info: poetry
summary: Dependency Management for Python
description: |
  Poetry helps you declare, manage and install dependencies of Python projects, 
  ensuring you have the right stack everywhere.
  
license: MIT

base: core20
grade: stable
confinement: strict

apps:
  poetry:
    command: etc/poetry
    environment:
      LC_ALL: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      POETRY_HOME: $SNAP/etc/poetry
      
parts:
  poetry:
    source: https://github.com/python-poetry/poetry
    source-type: git
    plugin: nil
    override-build: |
      git clone --recursive https://github.com/python-poetry/poetry
      cd poetry/
      python3 install-poetry.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/
      cp -r * $SNAPCRAFT_PART_INSTALL/etc/
      
    build-packages:
      - curl
      - tox
      - python3
      - python3-pip
    
    stage-packages:
      - python3
 
    override-pull: |    
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"   

